
# This workflow runs a set of yarn commands to compile, test and build a backstage application 
name: ci-cd to k8s

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "k8s" ]
  pull_request:
    branches: [ "k8s" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  REPO: backstage-from-scatch-demo
  IMAGE: backstage



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Install Dependencies
        run: yarn install  

      - name: Compile TypeScript
        run: yarn tsc


      - name: Run Unit Tests
        run: yarn test:all

      - name: Build the application
        run: yarn build:all

      # Ensure that the generated files are in the right place before the deploy step
      - name: Ensure Build Artifacts are Present
        run: |
          ls packages/backend/dist/
          echo "Artifacts: skeleton.tar.gz and bundle.tar.gz should be present"
# =========================
# CD — DEPLOY TO GCP VM
# =========================

  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Install Dependencies
        run: yarn install  

      - name: Build the application
        run: yarn build:all

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # # Step 3: Install gke-gcloud-auth-plugin
      # - name: Install gke-gcloud-auth-plugin
      #   run: |
      #     curl -sSL https://dl.google.com/cloudsdk/release/google-cloud-sdk.tar.gz | tar xz -C /tmp && \
      #     /tmp/google-cloud-sdk/install.sh -q && \
      #     /tmp/google-cloud-sdk/bin/gcloud components install gke-gcloud-auth-plugin 

      # Step 3: Setup Google Cloud SDK
      - uses: google-github-actions/setup-gcloud@v2

      # ✅ FIX: install plugin
      - name: Install GKE auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      # Step 4: Configure Docker to use Google Cloud's Container Registry
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker ${{ secrets.GKE_REGION }}-docker.pkg.dev

      # Step 5: Build the Docker image for your application
      - name: Build image
        run: |
          # Check if the files are there before the build
          ls packages/backend/dist/
          echo "Building Docker image..."
          echo "docker build -t ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO/$IMAGE:$GITHUB_SHA -f packages/backend/Dockerfile ." 
          docker build -t ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO/$IMAGE:$GITHUB_SHA -f packages/backend/Dockerfile .

      - name: Create GCR Repository if it doesn't exist
        run: |
          gcloud artifacts repositories describe $REPO \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --location=${{ secrets.GKE_REGION }} || \
          gcloud artifacts repositories create $REPO \
            --repository-format=docker \
            --location=${{ secrets.GKE_REGION }} \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Push image to GCR
        run: |
          docker push ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO/$IMAGE:$GITHUB_SHA

      # # Step 6: Push the built Docker image to Google Container Registry
      # - name: Push image to GCR
      #   run: |
      #     docker push ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO/$IMAGE:$GITHUB_SHA

      # Step 7: Get credentials for the GKE cluster to manage deployments
      - name: Get GKE Cluster credentials
        run: |
          gcloud container clusters get-credentials \
          ${{ secrets.GKE_CLUSTER }} \
          --region ${{ secrets.GKE_REGION }}

      # Step 8: Deploy the new Docker image to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          echo "Deploying to Kubernetes..."

          kubectl apply -f k8s/

          kubectl set image deployment/backstage \
          backstage=${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO/$IMAGE:$GITHUB_SHA \
          -n backstage

          echo "kubectl get pods -n backstage..."
          kubectl get pods -n backstage

          echo "kubectl describe pod -n backstage..."
          kubectl describe pod -n backstage