# cicd_2_gcp_cloudrun.yml - This GitHub Actions workflow is designed to automate the CI/CD process for a Backstage application. It consists of two main jobs: "build" and "deploy". The "build" job compiles the TypeScript code, runs unit tests, and builds the application. The "deploy" job authenticates with Google Cloud, builds a Docker image, pushes it to Google Container Registry, and deploys it to a Cloud Run service on GCP. The workflow is triggered on pushes and pull requests to the "k8s" branch.
# This workflow runs a set of yarn commands to compile, test and build a backstage application 
name: ci-cd to cloudrun

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "cloudrun" ]
  pull_request:
    branches: [ "cloudrun" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  REPO: backstage-from-scatch-demo
  IMAGE: backstage



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Install Dependencies
        run: yarn install  

      - name: Compile TypeScript
        run: yarn tsc


      - name: Run Unit Tests
        run: yarn test:all

      - name: Build the application
        run: yarn build:all

      # Ensure that the generated files are in the right place before the deploy step
      - name: Ensure Build Artifacts are Present
        run: |
          ls packages/backend/dist/
          echo "Artifacts: skeleton.tar.gz and bundle.tar.gz should be present"
# =========================
# CD — DEPLOY TO GCP CLOUD RUN
# =========================

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Install Dependencies
        run: yarn install  

      - name: Build the application
        run: yarn build:all
 
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud CLI
      - uses: google-github-actions/setup-gcloud@v2

      - name: Install GKE auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker ${{ secrets.GKE_REGION }}-docker.pkg.dev

      - name: Build image
        run: |
          # Check if the files are there before the build
          ls packages/backend/dist/
          echo "Building Docker image..." 
          docker build --no-cache \
          -t ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO/$IMAGE:$GITHUB_SHA \
          -f packages/backend/Dockerfile .

      - name: Create GCR Repository if it doesn't exist
        run: |
          gcloud artifacts repositories describe $REPO \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --location=${{ secrets.GKE_REGION }} || \
          gcloud artifacts repositories create $REPO \
            --repository-format=docker \
            --location=${{ secrets.GKE_REGION }} \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Push image to GCR
        run: |
          docker push ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO/$IMAGE:$GITHUB_SHA

      - name: Enable Google Cloud APIs
        run: |
          gcloud services enable \
            run.googleapis.com \
            cloudbuild.googleapis.com \
            containerregistry.googleapis.com  # Enable the necessary APIs for Cloud Run, Cloud Build, and Container Registry

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backstage \
            --image ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO/$IMAGE:$GITHUB_SHA \
            --platform managed \
            --region ${{ secrets.GKE_REGION }} \
            --allow-unauthenticated  # Deploy the Docker image to Google Cloud Run, making the service publicly accessible
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}  # Use the GCP project ID stored in secrets

      # - name: Get GKE Cluster credentials
      #   run: |
      #     gcloud container clusters get-credentials \
      #     ${{ secrets.GKE_CLUSTER }} \
      #     --region ${{ secrets.GKE_REGION }}


      # - name: Deploy to Kubernetes
      #   run: |
      #     echo "Deploying to Kubernetes..."

      #     kubectl apply -f k8s/

      #     kubectl set image deployment/backstage \
      #     backstage=${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO/$IMAGE:$GITHUB_SHA \
      #     -n backstage

      #     echo "kubectl get pods -n backstage..."
      #     kubectl get pods -n backstage

      #     echo "kubectl describe pod -n backstage..."
      #     kubectl describe pod -n backstage
